### ISSUE TITLE
The results of the multi-coil parallel test were poor

### ISSUE THREAD

**Issue by tianxiaoxiao88** [rmsouza01/CD-Deep-Cascade-MR-Reconstruction#1]
Hello,
  I'll use your model of **deep_cascade_unet_ki** for parallel imaging,but my test result as follow:
![QQ图片20191114095123](https://user-images.githubusercontent.com/40666451/68819924-8e5c6d00-06c4-11ea-9afd-768d077f85d2.png)
So I wanted to ask you if there was something wrong with my test code or something else.

**Comment by rmsouza01** [comment]
Hello,

Can you please post your code? It seems you are not treating complex values properly.

**Comment by tianxiaoxiao88** [comment]
> Hello,
> 
> Can you please post your code? It seems you are not treating complex values properly.

**Comment by tianxiaoxiao88** [comment]
Thank you very much. That's the mistake.

**Comment by tianxiaoxiao88** [comment]
Thank you very much.
